spring.application.name=spring-security

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

spring-security.app.secret=someRandomWords20192930129
spring-security.app.expirationMs=60000
